version: '3.8'
services:
  grpcserver:
    build: ./server/
    environment:
      - GRPC_PORT=${GRPC_PORT}
  grpcclient:
      build: ./client/
      environment:
        - API=${API}
        - PORT=${INT_PORT}
        - GRPC_PORT=${GRPC_PORT}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_SERVER=${REDIS_SERVER}
      ports:
        - ${PORT}:${INT_PORT}

  redis-1:
    image: redis
    container_name: redis-1
    ports:
      - ${REDIS_PORT}
    volumes:
      - redis_1_data:/data
    command: [ "redis-server", "--port ${REDIS_PORT}" ]
    networks:
      - redis-net

  redis-2:
    image: redis
    container_name: redis-2
    ports:
      - ${REDIS_PORT}
    volumes:
      - redis_2_data:/data
    command: [ "redis-server", "--port ${REDIS_PORT}" ]
    networks:
      - redis-net

  redis-3:
    image: redis
    container_name: redis-3
    ports:
      - ${REDIS_PORT}
    volumes:
      - redis_3_data:/data
    command: [ "redis-server", "--port ${REDIS_PORT}" , "--slaveof", "redis-1", "${REDIS_PORT}" ]
    networks:
      - redis-net

  redis-4:
    image: redis
    container_name: redis-4
    ports:
      - ${REDIS_PORT}
    volumes:
      - redis_4_data:/data
    command: [ "redis-server", "--port ${REDIS_PORT}" , "--slaveof", "redis-2", "${REDIS_PORT}" ]
    networks:
      - redis-net

  twem-proxy:
    image: tarantool/twemproxy
    command:
      - --verbose=11
    volumes:
      - ./nutcracker.yml:/conf/nutcracker.yml
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - redis-net
      - default

networks:
  default:
    driver: bridge
  redis-net:
    driver: bridge

volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
